# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-30 22:04
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('userName', models.CharField(max_length=200)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widgetRest.Chat')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=200)),
                ('comment_url', models.CharField(max_length=200)),
                ('comment_date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('element', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('poll_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widgetRest.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='PollQuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=200)),
                ('poll_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widgetRest.PollQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='UserActiveUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('last_ping', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widgetRest.PollQuestion')),
                ('question_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widgetRest.PollQuestionOption')),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_name', models.CharField(max_length=200, unique=True)),
                ('widget_title', models.CharField(max_length=200)),
                ('widget_icon', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('fileJS', models.CharField(max_length=200)),
                ('filesHTML', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='widgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='widgetRest.Comment')),
                ('url_tag', models.CharField(max_length=200)),
            ],
            bases=('widgetRest.comment',),
        ),
        migrations.AddField(
            model_name='useractiveurl',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widgetRest.Widget'),
        ),
        migrations.AddField(
            model_name='element',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widgetRest.Widget'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
