# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgetRest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
