# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151202175702 on 2016-03-31 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widgetRest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractiveurl',
            name='widget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='widgetRest.Widget'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
