# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widgetRest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActiveUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('last_ping', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widgetRest.User')),
            ],
        ),
        migrations.DeleteModel(
            name='ActiveUser',
        ),
    ]
