# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgetRest', '0002_poll_pollquestion_pollquestionoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestionoption',
            name='votes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
