# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgetRest', '0003_auto_20160412_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='widget_title',
            field=models.CharField(default='nada', max_length=200),
            preserve_default=False,
        ),
    ]
