# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 22:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('widgetRest', '0004_widget_widget_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='file',
            field=models.FileField(default=1, upload_to='.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widget',
            name='owner',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='widget',
            name='users',
            field=models.ManyToManyField(related_name='widgets', to=settings.AUTH_USER_MODEL),
        ),
    ]
